const WISHES = [
  ["", "Chúc chị năm 2025 luôn ngập tràn niềm vui, hạnh phúc và những điều tuyệt vời nhất 💖. Mong mỗi ngày đều là một ngày đáng nhớ của chị 🎉."],
  ["", "Hy vọng năm mới sẽ luôn giữ nụ cười trên môi chị, vì nụ cười đó khiến mọi thứ xung quanh chị thêm rạng rỡ 🌞."],
  ["", "Chúc chị một năm mới thật thành công, mọi dự định đều hoàn thành trọn vẹn và có thêm thật nhiều kỷ niệm đẹp 🎯."],
  ["", "Mong năm 2025 của chị sẽ đầy ắp những điều ngọt ngào và bất ngờ, mỗi ngày đều là một niềm vui mới 🌸."],
  ["", "Chúc chị luôn khỏe mạnh và tràn đầy năng lượng để làm mọi điều chị yêu thích 💪. Hãy thật hạnh phúc nhé!"],
  ["", "Mong chị luôn tự tin, không ngừng toả sáng và đạt được những đỉnh cao mới trong năm mới này 🌈."],
  ["", "Chúc chị một năm mới thật nhiều niềm vui, gặp được những điều bất ngờ đáng yêu và thú vị 🎁."],
  ["", "Hy vọng chị tìm thấy những niềm cảm hứng mới, để mỗi ngày trong năm 2025 đều đầy ý nghĩa và đáng nhớ ✨."],
  ["", "Chúc chị luôn được yêu thương và trân trọng, vì chị xứng đáng với những điều tốt đẹp nhất ❤️."],
  ["", "Mong chị luôn lạc quan và mạnh mẽ, bởi tinh thần tích cực của chị là nguồn cảm hứng cho mọi người xung quanh 🌻."],
  ["", "Chúc chị gặp được nhiều người bạn tuyệt vời, xây dựng thêm những mối quan hệ thật ý nghĩa 🤝."],
  ["", "Hy vọng chị đạt được mọi mục tiêu trong năm mới, vì chị xứng đáng với tất cả những thành công lớn nhất 🏆."],
  ["", "Chúc chị luôn hạnh phúc và mỗi ngày đều là một hành trình trưởng thành và yêu thương chính mình 💖."],
  ["", "Mong chị luôn tìm thấy niềm vui trong những điều nhỏ bé nhất của cuộc sống, để mỗi ngày đều thật đáng yêu 🌼."],
  ["", "Chúc chị một năm mới ngập tràn yêu thương và sự ấm áp từ gia đình, bạn bè và những người chị trân quý 🏠."],
  ["", "Hy vọng chị có những trải nghiệm mới thật đặc biệt, đáng nhớ để năm 2025 là một năm đầy màu sắc 🎨."],
  ["", "Chúc chị thật mạnh mẽ, vượt qua mọi thử thách và biến mọi khó khăn thành cơ hội để toả sáng 🦸‍♀️."],
  ["", "Mong chị tìm thấy sự bình yên và an nhiên trong tâm hồn, để sống một cuộc đời thật trọn vẹn 🧘‍♀️."],
  ["", "Chúc chị gặt hái thật nhiều thành công trong công việc, và luôn tìm thấy niềm vui trong từng cố gắng của mình 📈."],
  ["", "Hy vọng chị sẽ luôn được yêu thương, che chở, và cảm nhận sự bình yên trong từng khoảnh khắc của năm mới 🛡️."],
];
